# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "A command-line tool for viewing package documentation with a man-like interface"
  homepage "https://github.com/ka2n/miru"
  version "0.0.19"
  license "MIT"

  depends_on "gh" => :optional
  depends_on "glab" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ka2n/miru/releases/download/v0.0.19/miru_v0.0.19_darwin_amd64.tar.gz"
      sha256 "77e05b337e1e5fbd53e8c0a15e893933d725fa2d80aebf75b090837159ea4a1f"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ka2n/miru/releases/download/v0.0.19/miru_v0.0.19_darwin_arm64.tar.gz"
      sha256 "fe5d3b29d002ab583df568933aa57338b9d78ad414b60d994869763832e62914"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ka2n/miru/releases/download/v0.0.19/miru_v0.0.19_linux_amd64.tar.gz"
        sha256 "4f5cac4a6ece6c17032e78db29ebd3b2e71efb89b4d8e98d6a248486ea898180"

        def install
          bin.install "miru"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ka2n/miru/releases/download/v0.0.19/miru_v0.0.19_linux_arm64.tar.gz"
        sha256 "d127d2cbce0f94428b019c3404cdae6999055d35d11a7d329a563ec2e470d943"

        def install
          bin.install "miru"
        end
      end
    end
  end
end
