# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "A command-line tool for viewing package documentation with a man-like interface"
  homepage "https://github.com/ka2n/miru"
  version "0.0.4"
  license "MIT"

  depends_on "gh" => :optional
  depends_on "glab" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ka2n/miru/releases/download/v0.0.4/miru_v0.0.4_darwin_amd64.tar.gz"
      sha256 "e7c32426a046284b34f62b4f402f3649471ec9a664952b70c9da13a7b0729861"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ka2n/miru/releases/download/v0.0.4/miru_v0.0.4_darwin_arm64.tar.gz"
      sha256 "197e60408fc837f7b753cda3d34af17331d26ba682ce4113cd2d36ed00f1d784"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ka2n/miru/releases/download/v0.0.4/miru_v0.0.4_linux_amd64.tar.gz"
        sha256 "9dc73129997da218f2272d1460fbea6255d22c989e1cf7338e600b3e00ff7f4b"

        def install
          bin.install "miru"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ka2n/miru/releases/download/v0.0.4/miru_v0.0.4_linux_arm64.tar.gz"
        sha256 "7b9474b976a6b40ff444af222e5175a833359d12c48bdd015bba71667c60aea0"

        def install
          bin.install "miru"
        end
      end
    end
  end
end
