# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Miru < Formula
  desc "A command-line tool for viewing package documentation with a man-like interface"
  homepage "https://github.com/ka2n/miru"
  version "0.0.13"
  license "MIT"

  depends_on "gh" => :optional
  depends_on "glab" => :optional

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ka2n/miru/releases/download/v0.0.13/miru_v0.0.13_darwin_amd64.tar.gz"
      sha256 "6ef521250ae28f5832a6fa57f590e9b3c0a86a565e9db8cefcc39e9be5dc7cf2"

      def install
        bin.install "miru"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ka2n/miru/releases/download/v0.0.13/miru_v0.0.13_darwin_arm64.tar.gz"
      sha256 "423d2ad120db00824275259ed09728a3fee915224f05a2a607de34642b2ee8c7"

      def install
        bin.install "miru"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ka2n/miru/releases/download/v0.0.13/miru_v0.0.13_linux_amd64.tar.gz"
        sha256 "cd65569d8c9230f0dc7defeac26f10dd2cf3a21e4c9a8e386aa73ce0c48430a7"

        def install
          bin.install "miru"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ka2n/miru/releases/download/v0.0.13/miru_v0.0.13_linux_arm64.tar.gz"
        sha256 "68bf299c6c1bd5e1adc200478ed77e0f451bd9e607e24a209ddd81b268bc4a51"

        def install
          bin.install "miru"
        end
      end
    end
  end
end
